apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: canary-v2
  namespace: canary-production-canary
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  rules:
  - host: canary.com
    http:
      paths:
      - backend:
          serviceName: canary-v2
          servicePort: 8080
